### PR TITLE
Update of Go4's CMake specification: ROOT and RPATH

### PR DESCRIPTION
**Pull request by eamjensen**
Follow-up on issue #2 and pull request #3 .

As the latest version of Go4 requires ROOT version 6.24 or greater, I have modified the CMake specifications of Go4 to use ROOT's component namespaces (the "Modern CMake" way) in a fashion where CMake should be able to handle generation and subsequent build of Go4 from both local and system-wide installations of ROOT.

In addition, I have also modified CMake's RPATH handling in Go4 slightly, such that local as well as system-wide installations of the `go4` binary should be able to locate its dependent library files (`libGo4Widgets.so` and similar).

### CODE REVIEW

**Comment by linev** [comment]
Hi Erik,

Did you check with "normal" ROOT build? Which is not installed in the system paths?
I immediately get compilation error:

```
[ 54%] Built target G__Go4Base
Consolidate compiler generated dependencies of target Go4Base
[ 54%] Building CXX object CMakeFiles/Go4Base.dir/Go4StatusBase/TGo4BranchStatus.cxx.o
/home/linev/git/go4git/Go4StatusBase/TGo4BranchStatus.cxx:18:10: fatal error: TBranchElement.h: No such file or directory
   18 | #include "TBranchElement.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Go4Base.dir/build.make:230: CMakeFiles/Go4Base.dir/Go4StatusBase/TGo4BranchStatus.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:725: CMakeFiles/Go4Base.dir/all] Error 2
```


Most probably while you exclude:
```
include(${GO4_ROOT_DIR}/cmake/ROOTUseFile.cmake)
```
One probably can use something like:
```
find_package(ROOT)
include(${ROOT_USE_FILE})
```

Why current approach was implemented?
On the node many ROOT versions can be installed (I have several) and one can easily select wrong one before start compiling any go4-based analysis. Therefore I want to preserve path (aka ROOTSYS) which was used for Go4 compilation.

I could propose another PR which takes your solution when $ROOTSYS was not specified during Go4 compilation.

**Comment by linev** [comment]
Can you check updated https://github.com/gsi-ee/go4/pull/3 - if it works for you?
Once it is working - we could discuss other changes you proposed in PR #4.

**Comment by eamjensen** [comment]
Hi Sergey,

Thanks for your help!

This makes a lot of sense, and I did not do this check, sorry.

I have just tried configuring and building Go4 with the updated #3, and it works!
(System-wide install still has some issues, though, and I am confident that I fixed this issue in my PR #4. Another change in #4 is the usage of package library namespaces as opposed to "$-variables" -- which is what will continue being supported in the long-term, I think.)

However, if you provide CMake with the variable `ROOT_DIR` (i.e. `<PackageName>_DIR`) pointing to any of several local installations of ROOT containing a file `ROOTConfig.cmake`, do my changes still not work for you?

This is how I locate Go4, for example, in a CMake project when `Go4Config.cmake` is not in CMake's default search paths:

```cmake
# Filename: CMakeLists.txt
cmake_minimum_required(VERSION 3.15)
project(test)

find_package(Go4 REQUIRED)
```

A "naked" call to CMake gives an error,

```shell
erik@pensus:~/build> cmake .
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindGo4.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Go4", but
  CMake did not find one.

  Could not find a package configuration file provided by "Go4" with any of
  the following names:

    Go4Config.cmake
    go4-config.cmake

  Add the installation prefix of "Go4" to CMAKE_PREFIX_PATH or set "Go4_DIR"
  to a directory containing one of the above files.  If "Go4" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/erik/build/CMakeFiles/CMakeOutput.log".
```

but with an extra variable:

```shell
erik@pensus:~/build> cmake -DGo4_DIR=/usr/local/share .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/erik/build
```
it works.

Maybe this way does not fit into your overall project structure?

Cheers,
Erik

**Comment by linev** [comment]
> However, if you provide CMake with the variable ROOT_DIR (i.e. <PackageName>_DIR) pointing to any of several local 
> installations of ROOT containing a file ROOTConfig.cmake, do my changes still not work for you?

No, setting of ROOT_DIR does not help

`find_package(ROOT)` works without it, but it is not enough to compile ROOT-based code.
One have to import compilation flags and several other setting by calling `include(${ROOT_USE_FILE})`

For me is important that Go4 can be easily compiled just doing:

```
[shell] call path/to/root/bin/thisroot.sh 
[shell] cmake path/to/go4_source
[shell] make -j
```

And if ROOT installed system-wide, one should be able to skip first step.

I propose that I merge PR #3 and we step by step will try to apply proposed changes.

There is one problem with using direct library names like `ROOT::Core`. Not always all libraries are compiled by ROOT - like `libASImage.so`. Go4 able to work in both situations - with and without it. But writing `ROOT::ASImage` will always require that library is there. Therefore in some cases on may need to leave old notation. 

Also I want to understand your changes with RPATH. Can you provide them as separate PR?

And last comment - your editor remove new line at the end of files. It is not good practice - one better should keep them.

**Comment by eamjensen** [comment]
Hi Sergey,

I just tried again with the latest commit on the master branch of gsi-ee/go4, and now everything but the RPATH handling works for me. By modifying the RPATH handling in CMake slightly I am still/again able to use go4 system-wide as well.

Apologies for the confusion.
I am willing to commit only the changes that I made to the RPATH handling as a separate pull request, if you like.
It only amounts to a few modified lines in `cmake/modules/Go4BuildOptions.cmake` of the pull request I already made - completely independent of the other changes that I now see are better to retract.

Let me know how you prefer to proceed!

Cheers,
Erik

**Comment by linev** [comment]
Yes, 

Try to split your RPATH changes into separate PR and I will test them

**Comment by eamjensen** [comment]
Should be good now

**Comment by linev** [comment]
Erik, please create new PR with changes only for [cmake/modules/Go4BuildOptions.cmake](https://github.com/gsi-ee/go4/pull/4/files#diff-23124a1b8b20f27046bd6de1d8537a7fd56374f22ccb6be89eed608a5c3d7627).

Normally, when PR is created, one creates separate branch and put changes there.
Your own master branch must be in full sync of go4 master - otherwise you will have problems to create PRs.
If `upstream` is configured remote location to track go4 repository `git@github.com:gsi-ee/go4.git`, then do:

    git checkout master
    git fetch upstream
    git reset --hard upstream/master
    git checkout -b feature_branch
    ### commit all changes into feature_branch
    git push origin feature_branch

**Comment by eamjensen** [comment]
Done.
Please let me know how I can help in tidying up these other issues and pull requests.

**Comment by eamjensen** [comment]
Closing pull request, as PR #5 is the correct one

**Pull request closed without merging**
