### PR TITLE
Gui: safe a mouse click: use checkboxes instead of dropdown for logx, logy, logz

### PR DESCRIPTION
**Pull request by klenze**
The logness dropdown menus have only two options: lin and log. I think it is unlikely that ROOT will add a third setting. By using a checkbox, we can decrease the mouse clicks used to toggle by 50%.

### CODE REVIEW

**Comment by linev** [comment]
> I think it is unlikely that ROOT will add a third setting.

Plain ROOT not, but web-based graphic (JSROOT) has such possibility already.

If you start with `go4 --web` (but this requires web components compiled in ROOT as well), then you already now can select
via context menu `log2` draw option for axes. You can see such example here:

http://root.cern/js/latest/examples.htm#tcanvas_log2

**Comment by linev** [comment]
I test PR - it is fine.
But I prefer to keep `QComboBox` here - one could add `Log2` option where in the near future.

**Comment by klenze** [comment]
Re log2: From my understanding, that is just a log axis with ticks/labels at powers of two instead of powers of ten? Seems to me that there should be a TAxis::SetLogBase(double). (Or even TLogAxis: public TAbstractAxis {TLogAxis(double base=10);}, but that ship has sailed a long time ago).

**Comment by linev** [comment]
`TAxis::SetLogBase(double)` - there is no such functionality in plain ROOT

**Pull request closed without merging**
